### ISSUE TITLE
Empty output using guessAbiEncodedData function

### ISSUE THREAD

**Issue by ndkirillov** [openchainxyz/abi-guesser#1]
When using a function `guessAbiEncodedData` and passing any encoded abi data, it constantly returns null. What can be the issue? Is this function supposed to be used because there is not even a test case in a test file?

_For example:_
I am passing [this](https://etherscan.io/bytecode-decompiler?a=0x7E42c72DFbE07Cde83a6BaD535A1A97496Df1531) or any other bytecode to this function - `guessAbiEncodedData(test)` in a `test` variable. The variable is a string.
The return value is null.

Thanks for the help in advance.

**Comment by samczsun** [comment]
This package doesn't handle bytecode, only ABI-encoded data
